export const BREATH_PATTERNS = [
  {
    id: "box",
    name: "Box Breathing",
    description: "Calm focus",
    inhale: 4,
    hold1: 4,
    exhale: 4,
    hold2: 4,
  },
  {
    id: "relax",
    name: "Relaxing Breath",
    description: "Reduce stress",
    inhale: 4,
    hold1: 7,
    exhale: 8,
    hold2: 0,
  },
  {
    id: "energize",
    name: "Energy Boost",
    description: "Boost alertness",
    inhale: 3,
    hold1: 2,
    exhale: 3,
    hold2: 0,
  },
  {
    id: "balanced",
    name: "Balanced Breath",
    description: "Inner balance",
    inhale: 5,
    hold1: 5,
    exhale: 5,
    hold2: 0,
  },
  {
    id: "deep",
    name: "Deep Calm",
    description: "Long exhale",
    inhale: 4,
    hold1: 4,
    exhale: 6,
    hold2: 0,
  },
  {
    id: "cleansing",
    name: "Cleansing Breath",
    description: "Let go of tension",
    inhale: 5,
    hold1: 0,
    exhale: 8,
    hold2: 0,
  },
  {
    id: "ujjayi",
    name: "Ocean Breath",
    description: "Yogic flow",
    inhale: 5,
    hold1: 5,
    exhale: 5,
    hold2: 5,
  },
  {
    id: "grounding",
    name: "Grounding Breath",
    description: "Settle your energy",
    inhale: 6,
    hold1: 3,
    exhale: 6,
    hold2: 0,
  },
];
